#!/bin/bash

[[ -z ${debug_mode} ]] || set -x

_logfile="/tmp/tsend.$$"
_botfile="${HOME}/.tsendrc"

[[ -f ${_botfile} ]] && source ${_botfile} || true

function die(){
	echo "[error]: $@" >&2
	rm -f ${_logfile}
	exit 1
}

while (($#)) ; do
	case "$1" in
		-T|--token)
			TBOT_TOKEN="$1"
			shift
		;;
		-c|--chat_id)
			TBOT_CHAT_ID="$1"
			shift
		;;
		-f|--file)
			shift
			_file="$1"
			shift
		;;
		-a|--audio)
			_audio_file=1
			shift
		;;
		-P|--performer)
			[[ -n ${_audio_file} ]] || die "Use $1 for send audio file only!"
			shift
			_performer="$1"
			shift
		;;
		--title)
			[[ -n ${_audio_file} ]] || die "Use $1 for send audio file only!"
			shift
			_title="$1"
			shift
		;;
		-F|--photo)
			_photo_file=1
			shift
		;;
		-V|--video)
			_video_file=1
			shift
		;;
		-w|--width)
			[[ -n "${_video_file}" ]] || die "Use $1 for send video file only!"
			shift
			_video_width="$1"
			shift
		;;
		-H|--height)
			[[ -n "${_video_file}" ]] || die "Use $1 for send video file only!"
			shift
			_video_height="$1"
			shift
		;;
		-d|--disable-notification)
			_disable_notification=1
			shift
		;;
		-p|--protect-content)
			_protect_content=1
			shift
		;;
		-t|--thumb)
			shift
			_thumb="$1"
			shift
		;;
		*)
			_text="$1"
			shift
		;;
	esac
done

[[ -n "${TBOT_TOKEN}" ]] || die "token is empty. Please use \"-t <token>\" or set TBOT_TOKEN=<token> in ~/.tsendrc"
[[ -n "${TBOT_CHAT_ID}" ]] || die "chat_id is empty. Please use \"-c <chat_id>\" or set TBOT_CHAT_ID=<chat_id> in ~/.tsendrc"

_url="https://api.telegram.org/bot${TBOT_TOKEN}/"

if [[ -n "${_file}" ]] ; then
	[[ -f "${_file}" ]] || die "<${_file}> is not exist"
	# если отправляем аудиофайл
	if [[ -n "${_audio_file}" ]] ; then
		_url+="sendAudio?"
		_url+="${_performer:+performer=${_performer}}"
		_url+="${_title:+&title=${_title}}"
		_file_type="audio"
	elif [[ -n "${_photo_file}" ]] ; then
		_url+="sendPhoto?"
		_file_type="photo"
	elif [[ -n "${_video_file}" ]] ; then
		_url+="sendVideo?"
		_url+="${_video_width:+width=${_video_width}}"
		_url+="${_video_height:+&height=${_video_height}}"
		_file_type="video"
	else
		_url+="sendDocument?"
	fi
	_url+="${_text:+&caption=${_text}}"
	if [[ -n "${_thumb}" ]] ; then
		[[ -f "${_thumb}" ]] || die "<${_thumb}> is not exist"
	fi
else
	[[ -n "${_text}" ]] || die "empty message"
	_url+="sendMessage?"
	_url+="&text=\"${_text}\""
fi

_url+="&chat_id=${TBOT_CHAT_ID}"
_url+="${_disable_notification:+&disable_notification=true}"
_url+="${_protect_content:+&protect_content=true}"

curl \
	${_file:+-F ${_file_type:-document}=@${_file}} \
	${_thumb:+-F thumb=@${_thumb}} \
	"${_url}" \
	2>/dev/null \
	1>${_logfile}

if [[ $(jq -r .ok ${_logfile}) == false ]] ; then
	_err="$(jq -r .description ${_logfile})"
	die "bot return message: ${_err}"
fi
